### ISSUE TITLE
the indentation is wrong

### ISSUE THREAD

**Issue by nullscc** [jinkin1995/vue-json-edit#23]
Hi, 
     I'm a backend engineer, I love this tool, but I found the indentation showing below is not ok, using the example code in README, could you help me to figure it out?
![indentation](https://user-images.githubusercontent.com/17700282/64138471-d2fb9a80-ce2f-11e9-9273-0b1c43dd0cf6.png)

**Comment by rekatrina** [comment]
```
.clearfix {
        *zoom: 1;
 }
      
.clearfix:before,
.clearfix:after {
content: '';
        display: table;
}
      
 .clearfix:after {
        clear: both;
}
```
These css are necessary.

**Comment by nullscc** [comment]
ok, thank you for reply @rekatrina
