### ISSUE TITLE
"e.component is not a function"

### ISSUE THREAD

**Issue by sinisimattia** [jinkin1995/vue-json-edit#44]
Hi, I'm havig a bit of trouble registering your component.

If I register it globally it will then overwrite some of my CSS styles, but if I register it locally it gives me this error:

```
e.component is not a function
```

I'll provide my code down below.

```vue
// other imports here...
import JsonEditor from "vue-json-edit"

export default {
	components: {
                JsonEditor,
	},
};
```

Btw: the error is the same even when I register it with a name.

Thanks in advance for the help

**Comment by sinisimattia** [comment]
Resolved in: https://github.com/jinkin1995/vue-json-edit/pull/45

**Comment by tharindupr** [comment]
still having the same issue.
